manifest:
  defaults:
    revision: v0.3
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: zmk
      remote: zmkfirmware
      import: app/west.yml
    - name: zmk-stryke
      remote: zmkfirmware
      revision: main
      path: zmk-stryke  # <--- Changed this from 'config' to 'zmk-stryke'
  self:
    path: config
